FROM node:latest AS build

WORKDIR /my-react-app

COPY package*.json ./

RUN npm install

COPY . /my-react-app

RUN npm run build

CMD [ "npm", "start" ]


FROM nginx:alpine

COPY --from=build /my-react-app/build /usr/share/nginx/html

COPY nginx.conf /etc/nginx/sites-available/my_project

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
